### ISSUE TITLE
Download as zip excludes git-lfs files

### ISSUE THREAD

**Issue by PascalSoftwares** [GoaLitiuM/RmlUi#19]
A few .lib and .flax files are excluded from zip download because of lfs exclusion.
It might be appreciated to make 'releases' or change settings to include lfs files...

> [Managing Git LFS objects in archives](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-git-lfs-objects-in-archives-of-your-repository#managing-git-lfs-objects-in-archives)
> On GitHub.com, navigate to the main page of the repository.
> Under your repository name, click  Settings. If you cannot see the "Settings" tab, select the  dropdown menu, then click Settings.
> Screenshot of a repository header showing the tabs. The "Settings" tab is highlighted by a dark orange outline.
> Under "Archives", select or deselect Include Git LFS objects in archives.

**Comment by GoaLitiuM** [comment]
Fixed
