### ISSUE TITLE
Minimal requirement version?

### ISSUE THREAD

**Issue by PascalSoftwares** [GoaLitiuM/RmlUi#20]
On front page it says 
> Minimum supported Flax version: 1.6.
But for I tested official 1.6 version installation does not compatible with repository, referencing headers only exists in FlaxEngine bleeding edge repo. (And it has compatibility issue, at least in my case latest 'daily master branch' engine did not executed)

I understand some syntaxes in latest MSVS 2022 compiler has problem with standard 1.6 but the patch applied to engine to cope with VS2022 latest made RmlUI plugin incompatible to 1.6 even though it's mentioned in main README. I hope plugin to be compatible with 1.6, but at least to be fixed the requirement version part if it is not possible.

**Comment by GoaLitiuM** [comment]
Updated the minimum requirements to 1.7.1 due to MSVC compilation issue and incompatibility issue with packaged Editor installations. 1.7 built from source but not packaged is supported in plugin's current state.
